// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://swuipevtfwiulmxjmsvr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN3dWlwZXZ0ZndpdWxteGptc3ZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczNTg0NTAsImV4cCI6MjA2MjkzNDQ1MH0.YVZFqKwJnMYaFP2PYr2XJekw0x0tlGtC2iibooOTrEI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);